[package]
name = "discord-bot"
version = "0.1.0"
authors = ["lewisfff <lewisfff>"]
edition = "2018"

[dependencies]
serenity = "0.5.11"
env_logger = "0.4.3"
kankyo = "0.1.1"
log = "0.4.6"
rand = "0.4.5"